// ═══════════════════════════════════════════════
// PokéVault — Static Game Data
// Pokémon type sets and moveset database
// ═══════════════════════════════════════════════
'use strict';

// RULES defined in config.js

// ═══════════════════════════════════════════════
// SHADOW-SPECIFIC MOVESETS (differ from normal)
// ═══════════════════════════════════════════════
const SHADOW_MOVES = {
  // Shadow versions often prefer faster charging moves
  Machamp:{G:['Counter','Rock Slide','Cross Chop'],U:['Counter','Rock Slide','Cross Chop'],M:['Counter','Rock Slide','Cross Chop']},
  Gengar:{G:['Lick','Shadow Ball','Shadow Punch'],U:['Shadow Claw','Shadow Ball'],M:['Shadow Claw','Shadow Ball']},
  Dragonite:{M:['Dragon Tail','Dragon Claw','Hurricane']}, // Dragon Claw charges faster for shadow
  Swampert:{G:['Mud Shot','Hydro Cannon','Sludge Wave'],U:['Mud Shot','Hydro Cannon','Sludge Wave']},
  Gardevoir:{G:['Charm','Shadow Ball','Synchronoise'],U:['Charm','Shadow Ball','Synchronoise']},
  Salamence:{M:['Dragon Tail','Outrage','Fire Blast']},
  Mewtwo:{M:['Confusion','Shadow Ball','Psystrike']}, // Shadow Ball better on shadow
  Charizard:{G:['Fire Spin','Blast Burn','Dragon Claw'],M:['Fire Spin','Blast Burn','Dragon Claw']},
  Tyranitar:{M:['Smack Down','Crunch','Stone Edge']},
  Gyarados:{G:['Waterfall','Aqua Tail','Crunch'],U:['Waterfall','Hydro Pump','Crunch']},
  Snorlax:{G:['Lick','Body Slam','Skull Bash']},
  Flygon:{G:['Mud Shot','Dragon Claw','Earth Power'],U:['Mud Shot','Dragon Claw','Earth Power']},
  Electivire:{U:['Thunder Shock','Wild Charge','Ice Punch']},
  Magmortar:{U:['Fire Spin','Thunderbolt','Fire Punch']},
  Nidoqueen:{G:['Poison Jab','Poison Fang','Earth Power']},
  Politoed:{G:['Mud Shot','Weather Ball','Blizzard']},
  Victreebel:{G:['Razor Leaf','Leaf Blade','Acid Spray']},
  Hypno:{G:['Confusion','Shadow Ball','Focus Blast']},
};

// ═══════════════════════════════════════════════
// POKEMON CLASSIFICATIONS
// ═══════════════════════════════════════════════
const LEGENDARY = new Set(['Articuno','Zapdos','Moltres','Mewtwo','Raikou','Entei','Suicune',
  'Lugia','Ho-Oh','Regirock','Regice','Registeel','Latias','Latios','Kyogre','Groudon',
  'Rayquaza','Uxie','Mesprit','Azelf','Dialga','Palkia','Heatran','Regigigas','Giratina',
  'Cresselia','Cobalion','Terrakion','Virizion','Tornadus','Thundurus','Reshiram','Zekrom',
  'Landorus','Kyurem','Xerneas','Yveltal','Zygarde','Tapu Koko','Tapu Lele','Tapu Bulu',
  'Tapu Fini','Solgaleo','Lunala','Necrozma','Zacian','Zamazenta','Eternatus','Urshifu',
  'Regieleki','Regidrago','Glastrier','Spectrier','Calyrex','Enamorus','Koraidon','Miraidon',
  'Gouging Fire','Raging Bolt','Iron Boulder','Iron Crown','Terapagos']);
const MYTHICAL = new Set(['Mew','Celebi','Jirachi','Deoxys','Phione','Manaphy','Darkrai',
  'Shaymin','Arceus','Victini','Keldeo','Meloetta','Genesect','Diancie','Hoopa','Volcanion',
  'Magearna','Marshadow','Zeraora','Meltan','Melmetal','Zarude','Pecharunt']);
const ULTRA_BEAST = new Set(['Nihilego','Buzzwole','Pheromosa','Xurkitree','Celesteela',
  'Kartana','Guzzlord','Poipole','Naganadel','Stakataka','Blacephalon']);

function getPokeType(name) {
  if (LEGENDARY.has(name)) return 'Legendary';
  if (MYTHICAL.has(name)) return 'Mythical';
  if (ULTRA_BEAST.has(name)) return 'Ultra Beast';
  if (name.startsWith('Mega ') || name.endsWith(' Mega')) return 'Mega';
  return null;
}

// ── Best moves database ──────────────────────────────
const BEST_MOVES = {
  Feraligatr:{G:['Waterfall','Hydro Cannon','Ice Beam'],U:['Waterfall','Hydro Cannon','Ice Beam'],M:['Waterfall','Hydro Cannon','Crunch']},
  Croconaw:{G:['Waterfall','Aqua Tail'],L:['Waterfall','Aqua Tail']},
  Totodile:{L:['Water Gun','Aqua Tail']},
  Charizard:{G:['Fire Spin','Blast Burn','Dragon Claw'],U:['Fire Spin','Blast Burn','Dragon Claw'],M:['Fire Spin','Blast Burn','Overheat']},
  Blastoise:{G:['Water Gun','Hydro Cannon','Ice Beam'],U:['Water Gun','Hydro Cannon','Ice Beam']},
  Venusaur:{G:['Vine Whip','Frenzy Plant','Sludge Bomb'],U:['Vine Whip','Frenzy Plant','Sludge Bomb']},
  Umbreon:{G:['Snarl','Foul Play','Last Resort'],U:['Snarl','Foul Play','Last Resort']},
  Sylveon:{G:['Charm','Moonblast','Psyshock'],U:['Charm','Moonblast','Psyshock']},
  Espeon:{G:['Confusion','Psychic','Shadow Ball'],U:['Confusion','Psychic','Shadow Ball']},
  Vaporeon:{G:['Water Gun','Aqua Tail','Last Resort'],U:['Water Gun','Hydro Pump']},
  Glaceon:{G:['Ice Shard','Avalanche'],U:['Ice Shard','Avalanche']},
  Leafeon:{G:['Razor Leaf','Leaf Blade']},
  Jolteon:{G:['Thunder Shock','Discharge','Thunderbolt']},
  Flareon:{M:['Fire Spin','Flamethrower','Superpower']},
  Azumarill:{G:['Bubble','Ice Beam','Play Rough'],L:['Bubble','Ice Beam','Play Rough']},
  Machamp:{G:['Counter','Cross Chop','Rock Slide'],U:['Counter','Cross Chop','Rock Slide'],M:['Counter','Cross Chop','Rock Slide']},
  Gengar:{G:['Lick','Shadow Ball','Shadow Punch'],U:['Shadow Claw','Shadow Ball'],M:['Shadow Claw','Shadow Ball']},
  Swampert:{G:['Mud Shot','Hydro Cannon','Earthquake'],U:['Mud Shot','Hydro Cannon','Earthquake']},
  Medicham:{G:['Counter','Ice Punch','Psychic']},
  Registeel:{G:['Lock On','Flash Cannon','Focus Blast'],U:['Lock On','Flash Cannon','Focus Blast']},
  Giratina:{U:['Shadow Claw','Dragon Claw','Shadow Sneak'],G:['Shadow Claw','Dragon Claw','Shadow Sneak']},
  Garchomp:{M:['Mud Shot','Earth Power','Outrage']},
  Mewtwo:{M:['Confusion','Psystrike','Ice Beam']},
  Dragonite:{M:['Dragon Breath','Draco Meteor','Hurricane']},
  Tyranitar:{G:['Smack Down','Stone Edge','Crunch'],U:['Smack Down','Stone Edge','Crunch'],M:['Smack Down','Stone Edge','Crunch']},
  Lucario:{G:['Counter','Power-Up Punch','Shadow Ball'],M:['Counter','Aura Sphere','Shadow Ball']},
  Togekiss:{G:['Charm','Ancient Power','Aerial Ace'],U:['Charm','Ancient Power','Flamethrower']},
  Lickitung:{G:['Lick','Body Slam','Power Whip']},
  Walrein:{G:['Powder Snow','Icicle Spear','Earthquake']},
  Trevenant:{G:['Shadow Claw','Shadow Ball','Seed Bomb']},
  Obstagoon:{G:['Counter','Night Slash','Cross Chop']},
  Skarmory:{G:['Air Slash','Brave Bird','Flash Cannon']},
  Altaria:{G:['Dragon Breath','Sky Attack','Moonblast']},
  Pelipper:{G:['Wing Attack','Weather Ball','Hurricane']},
  Cresselia:{G:['Psycho Cut','Grass Knot','Moonblast'],U:['Psycho Cut','Grass Knot','Moonblast']},
  Gallade:{G:['Confusion','Leaf Blade','Close Combat'],U:['Confusion','Leaf Blade','Close Combat']},
  Stunfisk:{G:['Mud Shot','Discharge','Rock Slide']},
  Sableye:{G:['Shadow Claw','Foul Play','Return']},
  Whiscash:{G:['Mud Shot','Mud Bomb','Blizzard']},
  Dewgong:{G:['Ice Shard','Icy Wind','Water Pulse']},
  Arcanine:{G:['Snarl','Flamethrower','Wild Charge'],U:['Snarl','Fire Blast','Crunch']},
  Nidoqueen:{G:['Poison Jab','Poison Fang','Earth Power']},
  Ferrothorn:{G:['Bullet Seed','Power Whip','Flash Cannon'],U:['Bullet Seed','Power Whip','Flash Cannon']},
  Tropius:{G:['Razor Leaf','Leaf Blade','Aerial Ace']},
  Politoed:{G:['Mud Shot','Weather Ball','Blizzard']},
  Clefable:{G:['Charm','Moonblast','Meteor Mash']},
  Bastiodon:{G:['Smack Down','Stone Edge','Flamethrower'],L:['Smack Down','Stone Edge','Flamethrower']},
  Drifblim:{G:['Hex','Icy Wind','Shadow Ball']},
  Lugia:{U:['Dragon Tail','Aeroblast','Sky Attack'],M:['Dragon Tail','Aeroblast','Sky Attack']},
  Dialga:{M:['Dragon Breath','Iron Head','Thunder']},
  Rayquaza:{M:['Dragon Tail','Breaking Swipe','Aerial Ace']},
  Kyogre:{M:['Waterfall','Surf','Blizzard']},
  Groudon:{M:['Mud Shot','Precipice Blades','Fire Punch']},
  Zacian:{M:['Quick Attack','Close Combat','Play Rough']},
  Chandelure:{U:['Hex','Shadow Ball','Overheat']},
  Excadrill:{U:['Mud Shot','Drill Run','Rock Slide']},
  Conkeldurr:{U:['Counter','Dynamic Punch','Stone Edge']},
  Suicune:{G:['Ice Fang','Ice Beam','Bubble Beam']},
  Raikou:{U:['Thunder Shock','Wild Charge','Shadow Ball']},
  Entei:{U:['Fire Fang','Overheat','Iron Head']},
  Zapdos:{M:['Thunder Shock','Thunderbolt','Drill Peck'],G:['Thunder Shock','Ancient Power','Drill Peck']},
  Moltres:{M:['Fire Spin','Sky Attack','Ancient Power'],U:['Fire Spin','Sky Attack','Ancient Power']},
  Articuno:{G:['Ice Shard','Icy Wind','Ancient Power'],U:['Ice Shard','Icy Wind','Hurricane']},
  Golduck:{G:['Confusion','Hydro Pump','Psychic'],U:['Confusion','Hydro Pump','Psychic']},
  Oranguru:{U:['Confusion','Foul Play','Psychic']},
  Lycanroc:{G:['Rock Throw','Stone Edge','Crunch']},
  Rockruff:{L:['Rock Throw','Crunch']},
  Poliwrath:{G:['Counter','Ice Punch','Dynamic Punch']},
  Muk:{G:['Poison Jab','Gunk Shot','Thunder Punch']},
  Pidgeot:{G:['Gust','Feather Dance','Brave Bird']},
  Glimmora:{G:['Rollout','Power Gem','Sludge Bomb'],U:['Rollout','Power Gem','Sludge Bomb']},
  Cinderace:{G:['Quick Attack','Pyro Ball'],U:['Quick Attack','Pyro Ball'],M:['Quick Attack','Pyro Ball']},
};

// ═══════════════════════════════════════════════
// FORM UTILITIES
// ═══════════════════════════════════════════════
const FORM_DROPDOWNS = {
  Vivillon:   ['Unknown','Archipelago','Continental','Elegant','Fancy','Garden','High Plains','Icy Snow','Jungle','Marine','Meadow','Modern','Monsoon','Ocean','Polar','River','Sandstorm','Savanna','Sun','Tundra','Poke Ball'],
  Scatterbug: ['Unknown','Archipelago','Continental','Elegant','Fancy','Garden','High Plains','Icy Snow','Jungle','Marine','Meadow','Modern','Monsoon','Ocean','Polar','River','Sandstorm','Savanna','Sun','Tundra','Poke Ball'],
  Spewpa:     ['Unknown','Archipelago','Continental','Elegant','Fancy','Garden','High Plains','Icy Snow','Jungle','Marine','Meadow','Modern','Monsoon','Ocean','Polar','River','Sandstorm','Savanna','Sun','Tundra','Poke Ball'],
  'Flabébé':  ['Unknown','Red','Yellow','Orange','Blue','White'],
  Floette:    ['Unknown','Red','Yellow','Orange','Blue','White'],
  Florges:    ['Unknown','Red','Yellow','Orange','Blue','White'],
  Furfrou:    ['Unknown','Natural','Heart','Star','Diamond','Debutante','Matron','Dandy','La Reine','Kabuki','Pharaoh'],
  Shellos:    ['Unknown','West Sea','East Sea'],
  Gastrodon:  ['Unknown','West Sea','East Sea'],
  Burmy:      ['Unknown','Plant Cloak','Sandy Cloak','Trash Cloak'],
};

const FORM_SEARCH = {
  'Polar':'polar','Marine':'marine','Savanna':'savanna','Jungle':'jungle',
  'Meadow':'meadow','Modern':'modern','Tundra':'tundra','Continental':'continental',
  'Garden':'garden','Elegant':'elegant','Icy Snow':'icysnow','Monsoon':'monsoon',
  'High Plains':'highplains','River':'river','Sandstorm':'sandstorm',
  'Sun':'sun','Archipelago':'archipelago','Ocean':'ocean','Fancy':'fancy',
  'Poke Ball':'pokeball','Red':'red flower','Yellow':'yellow flower',
  'Orange':'orange flower','Blue':'blue flower','White':'white flower',
  'West Sea':'west','East Sea':'east',
  'Plant Cloak':'plant','Sandy Cloak':'sandy','Trash Cloak':'trash',
};

const COSTUME_SPECIES = new Set([
  'Pikachu','Raichu','Pichu','Gengar','Haunter','Gastly',
  'Hoothoot','Noctowl','Squirtle','Wartortle','Blastoise',
  'Charmander','Charmeleon','Charizard','Bulbasaur','Ivysaur','Venusaur',
  'Eevee','Snorlax'
]);

// ═══════════════════════════════════════════════
// VALID EVOLUTIONS — hardcoded from Pokégenie data
// Used to validate evolution targets and reject scan errors
// ═══════════════════════════════════════════════
const VALID_EVOLUTIONS = {
  'Abra':['Kadabra','Alakazam'],'Aipom':['Ambipom'],'Amaura':['Aurorus'],
  'Anorith':['Armaldo'],'Applin':['Flapple','Appletun','Dipplin','Hydrapple'],
  'Archen':['Archeops'],'Aron':['Lairon','Aggron'],'Axew':['Fraxure','Haxorus'],
  'Azurill':['Marill','Azumarill'],'Bagon':['Shelgon','Salamence'],
  'Baltoy':['Claydol'],'Barboach':['Whiscash'],'Bayleef':['Meganium'],
  'Beldum':['Metang','Metagross'],'Bellsprout':['Weepinbell','Victreebel'],
  'Bergmite':['Avalugg'],'Bidoof':['Bibarel'],'Binacle':['Barbaracle'],
  'Bisharp':['Kingambit'],'Blipbug':['Dottler','Orbeetle'],'Blitzle':['Zebstrika'],
  'Boldore':['Gigalith'],'Bonsly':['Sudowoodo'],
  'Bounsweet':['Steenee','Tsareena'],'Braixen':['Delphox'],
  'Brionne':['Primarina'],'Bronzor':['Bronzong'],'Buizel':['Floatzel'],
  'Bulbasaur':['Ivysaur','Venusaur'],'Buneary':['Lopunny'],
  'Bunnelby':['Diggersby'],'Burmy':['Wormadam','Mothim'],
  'Cacnea':['Cacturne'],'Carvanha':['Sharpedo'],'Cascoon':['Dustox'],
  'Caterpie':['Metapod','Butterfree'],'Cetoddle':['Cetitan'],
  'Chansey':['Blissey'],'Charcadet':['Armarouge','Ceruledge'],
  'Charjabug':['Vikavolt'],'Charmander':['Charmeleon','Charizard'],
  'Charmeleon':['Charizard'],'Cherubi':['Cherrim'],
  'Chespin':['Quilladin','Chesnaught'],'Chikorita':['Bayleef','Meganium'],
  'Chimchar':['Monferno','Infernape'],'Chinchou':['Lanturn'],
  'Chingling':['Chimecho'],'Clamperl':['Huntail','Gorebyss'],
  'Clauncher':['Clawitzer'],'Clefairy':['Clefable'],'Cleffa':['Clefairy','Clefable'],
  'Clobbopus':['Grapploct'],'Combee':['Vespiquen'],'Corphish':['Crawdaunt'],
  'Corsola':['Cursola'],'Cosmoem':['Solgaleo','Lunala'],
  'Cottonee':['Whimsicott'],'Crabrawler':['Crabominable'],
  'Cranidos':['Rampardos'],'Croagunk':['Toxicroak'],'Crocalor':['Skeledirge'],'Croconaw':['Feraligatr'],
  'Cubchoo':['Beartic'],'Cubone':['Marowak'],'Cutiefly':['Ribombee'],
  'Cyndaquil':['Quilava','Typhlosion'],'Dartrix':['Decidueye'],
  'Darumaka':['Darmanitan'],'Deerling':['Sawsbuck'],
  'Deino':['Zweilous','Hydreigon'],'Dewott':['Samurott'],'Dewpider':['Araquanid'],
  'Diglett':['Dugtrio'],'Doduo':['Dodrio'],'Dolliv':['Arboliva'],
  'Dottler':['Orbeetle'],'Dragonair':['Dragonite'],'Dratini':['Dragonair','Dragonite'],
  'Dreepy':['Drakloak','Dragapult'],'Drifloon':['Drifblim'],'Drilbur':['Excadrill'],
  'Drizzile':['Inteleon'],'Drowzee':['Hypno'],'Ducklett':['Swanna'],
  'Dunsparce':['Dudunsparce'],'Dusclops':['Dusknoir'],
  'Duskull':['Dusclops','Dusknoir'],'Dwebble':['Crustle'],
  'Eelektrik':['Eelektross'],
  'Eevee':['Vaporeon','Jolteon','Flareon','Espeon','Umbreon','Leafeon','Glaceon','Sylveon'],
  'Ekans':['Arbok'],'Electabuzz':['Electivire'],'Electrike':['Manectric'],
  'Elekid':['Electabuzz','Electivire'],'Elgyem':['Beheeyem'],
  'Espurr':['Meowstic'],'Exeggcute':['Exeggutor'],
  'Farfetch’d':['Sirfetch’d'],'Feebas':['Milotic'],
  'Fennekin':['Braixen','Delphox'],'Ferroseed':['Ferrothorn'],
  'Fidough':['Dachsbun'],'Finneon':['Lumineon'],
  'Flaaffy':['Ampharos'],
  'Flabébé':['Floette','Florges'],'Fletchling':['Fletchinder','Talonflame'],
  'Floette':['Florges'],'Fomantis':['Lurantis'],'Foongus':['Amoonguss'],
  'Fraxure':['Haxorus'],'Frigibax':['Arctibax','Baxcalibur'],
  'Frillish':['Jellicent'],'Froakie':['Frogadier','Greninja'],
  'Frogadier':['Greninja'],'Fuecoco':['Crocalor','Skeledirge'],
  'Gastly':['Haunter','Gengar'],'Geodude':['Graveler','Golem'],
  'Gible':['Gabite','Garchomp'],'Gimmighoul':['Gholdengo'],
  'Girafarig':['Farigiraf'],'Glameow':['Purugly'],'Gligar':['Gliscor'],
  'Glimmet':['Glimmora'],'Gloom':['Vileplume','Bellossom'],
  'Golbat':['Crobat'],'Goldeen':['Seaking'],'Golett':['Golurk'],
  'Goomy':['Sliggoo','Goodra'],'Gossifleur':['Eldegoss'],
  'Gothita':['Gothorita','Gothitelle'],'Gothorita':['Gothitelle'],
  'Greavard':['Houndstone'],'Grimer':['Muk'],'Grookey':['Thwackey','Rillaboom'],
  'Grotle':['Torterra'],'Grovyle':['Sceptile'],'Growlithe':['Arcanine'],
  'Grubbin':['Charjabug','Vikavolt'],'Gulpin':['Swalot'],
  'Gurdurr':['Conkeldurr'],'Happiny':['Chansey','Blissey'],
  'Hatenna':['Hattrem','Hatterene'],'Haunter':['Gengar'],
  'Helioptile':['Heliolisk'],'Herdier':['Stoutland'],
  'Hippopotas':['Hippowdon'],'Honedge':['Doublade','Aegislash'],
  'Hoothoot':['Noctowl'],'Hoppip':['Skiploom','Jumpluff'],
  'Horsea':['Seadra','Kingdra'],'Houndour':['Houndoom'],
  'Igglybuff':['Jigglypuff','Wigglytuff'],'Impidimp':['Morgrem','Grimmsnarl'],
  'Inkay':['Malamar'],'Ivysaur':['Venusaur'],
  'Jangmo-o':['Hakamo-o','Kommo-o'],'Jigglypuff':['Wigglytuff'],
  'Joltik':['Galvantula'],'Kabuto':['Kabutops'],
  'Kadabra':['Alakazam'],'Kakuna':['Beedrill'],
  'Karrablast':['Escavalier'],'Kirlia':['Gardevoir','Gallade'],
  'Klang':['Klinklang'],'Klink':['Klang','Klinklang'],'Koffing':['Weezing'],
  'Krabby':['Kingler'],'Kricketot':['Kricketune'],'Kubfu':['Urshifu'],
  'Lampent':['Chandelure'],'Larvesta':['Volcarona'],
  'Larvitar':['Pupitar','Tyranitar'],'Lechonk':['Oinkologne'],
  'Ledyba':['Ledian'],'Lickitung':['Lickilicky'],'Lileep':['Cradily'],
  'Lillipup':['Herdier','Stoutland'],'Linoone':['Obstagoon'],
  'Litleo':['Pyroar'],'Litten':['Torracat','Incineroar'],
  'Litwick':['Lampent','Chandelure'],'Lombre':['Ludicolo'],
  'Lotad':['Lombre','Ludicolo'],'Loudred':['Exploud'],
  'Luxio':['Luxray'],'Machop':['Machoke','Machamp'],
  'Magby':['Magmar','Magmortar'],'Magikarp':['Gyarados'],
  'Magmar':['Magmortar'],'Magnemite':['Magneton','Magnezone'],
  'Magneton':['Magnezone'],'Makuhita':['Hariyama'],
  'Mankey':['Primeape','Annihilape'],'Mantyke':['Mantine'],
  'Mareanie':['Toxapex'],'Mareep':['Flaaffy','Ampharos'],
  'Marill':['Azumarill'],'Meditite':['Medicham'],'Meltan':['Melmetal'],
  'Meowth':['Persian','Perrserker'],'Metapod':['Butterfree'],
  'Mienfoo':['Mienshao'],'Mime Jr.':['Mr. Mime'],'Minccino':['Cinccino'],
  'Misdreavus':['Mismagius'],'Monferno':['Infernape'],
  'Morelull':['Shiinotic'],'Mr. Mime':['Mr. Rime'],
  'Mudkip':['Marshtomp','Swampert'],'Munchlax':['Snorlax'],
  'Munna':['Musharna'],'Murkrow':['Honchkrow'],
  'Nacli':['Naclstack','Garganacl'],'Natu':['Xatu'],'Nickit':['Thievul'],
  'Nidoran♀':['Nidorina','Nidoqueen'],
  'Nidoran♂':['Nidorino','Nidoking'],
  'Nidorino':['Nidoking'],'Nincada':['Ninjask','Shedinja'],
  'Noibat':['Noivern'],'Nosepass':['Probopass'],'Numel':['Camerupt'],
  'Nuzleaf':['Shiftry'],'Nymble':['Lokix'],
  'Oddish':['Gloom','Vileplume','Bellossom'],'Omanyte':['Omastar'],
  'Onix':['Steelix'],'Oshawott':['Dewott','Samurott'],
  'Palpitoad':['Seismitoad'],'Pancham':['Pangoro'],
  'Panpour':['Simipour'],'Pansage':['Simisage'],'Pansear':['Simisear'],
  'Paras':['Parasect'],'Patrat':['Watchog'],
  'Pawmi':['Pawmo','Pawmot'],'Pawmo':['Pawmot'],
  'Pawniard':['Bisharp','Kingambit'],'Petilil':['Lilligant'],
  'Phanpy':['Donphan'],'Phantump':['Trevenant'],
  'Pichu':['Pikachu','Raichu'],'Pidgeotto':['Pidgeot'],
  'Pidgey':['Pidgeotto','Pidgeot'],'Pidove':['Tranquill','Unfezant'],
  'Pignite':['Emboar'],'Pikachu':['Raichu'],
  'Pikipek':['Trumbeak','Toucannon'],'Piloswine':['Mamoswine'],
  'Pineco':['Forretress'],'Piplup':['Prinplup','Empoleon'],
  'Poliwag':['Poliwhirl','Poliwrath','Politoed'],
  'Ponyta':['Rapidash'],'Poochyena':['Mightyena'],
  'Popplio':['Brionne','Primarina'],'Porygon':['Porygon2','Porygon-Z'],
  'Porygon2':['Porygon-Z'],'Primeape':['Annihilape'],
  'Psyduck':['Golduck'],'Pumpkaboo':['Gourgeist'],
  'Purrloin':['Liepard'],'Quaxly':['Quaxwell','Quaquaval'],
  'Quaxwell':['Quaquaval'],'Qwilfish':['Overqwil'],
  'Raboot':['Cinderace'],'Ralts':['Kirlia','Gardevoir','Gallade'],
  'Rattata':['Raticate'],'Remoraid':['Octillery'],
  'Rhydon':['Rhyperior'],'Rhyhorn':['Rhydon','Rhyperior'],
  'Riolu':['Lucario'],'Rockruff':['Lycanroc'],
  'Roggenrola':['Boldore','Gigalith'],'Rolycoly':['Carkol','Coalossal'],
  'Rookidee':['Corvisquire','Corviknight'],'Roselia':['Roserade'],
  'Rowlet':['Dartrix','Decidueye'],'Rufflet':['Braviary'],
  'Salandit':['Salazzle'],'Sandile':['Krokorok','Krookodile'],
  'Sandshrew':['Sandslash'],'Sandygast':['Palossand'],
  'Scatterbug':['Spewpa','Vivillon'],'Scorbunny':['Raboot','Cinderace'],
  'Scraggy':['Scrafty'],'Scyther':['Scizor','Kleavor'],
  'Seadra':['Kingdra'],'Sealeo':['Walrein'],
  'Seedot':['Nuzleaf','Shiftry'],'Seel':['Dewgong'],
  'Sentret':['Furret'],'Servine':['Serperior'],
  'Sewaddle':['Swadloon','Leavanny'],'Shelgon':['Salamence'],
  'Shellder':['Cloyster'],'Shellos':['Gastrodon'],
  'Shelmet':['Accelgor'],'Shieldon':['Bastiodon'],
  'Shinx':['Luxio','Luxray'],'Shroodle':['Grafaiai'],
  'Shroomish':['Breloom'],'Shuppet':['Banette'],
  'Silcoon':['Beautifly'],'Sinistea':['Polteageist'],
  'Sizzlipede':['Centiskorch'],'Skiddo':['Gogoat'],
  'Skiploom':['Jumpluff'],'Skitty':['Delcatty'],
  'Skorupi':['Drapion'],'Skrelp':['Dragalge'],'Skwovet':['Greedent'],
  'Slakoth':['Vigoroth','Slaking'],'Sliggoo':['Goodra'],
  'Slowpoke':['Slowbro','Slowking'],'Slugma':['Magcargo'],
  'Smoliv':['Dolliv','Arboliva'],'Smoochum':['Jynx'],
  'Sneasel':['Weavile','Sneasler'],'Snivy':['Servine','Serperior'],
  'Snom':['Frosmoth'],'Snorunt':['Glalie','Froslass'],
  'Snover':['Abomasnow'],'Snubbull':['Granbull'],
  'Sobble':['Drizzile','Inteleon'],'Solosis':['Duosion','Reuniclus'],
  'Spearow':['Fearow'],'Spewpa':['Vivillon'],
  'Spheal':['Sealeo','Walrein'],'Spinarak':['Ariados'],
  'Spoink':['Grumpig'],'Sprigatito':['Floragato','Meowscarada'],
  'Spritzee':['Aromatisse'],'Squirtle':['Wartortle','Blastoise'],
  'Stantler':['Wyrdeer'],'Staravia':['Staraptor'],
  'Starly':['Staravia','Staraptor'],'Staryu':['Starmie'],
  'Steenee':['Tsareena'],'Stufful':['Bewear'],
  'Stunky':['Skuntank'],'Sunkern':['Sunflora'],
  'Surskit':['Masquerain'],'Swablu':['Altaria'],
  'Swadloon':['Leavanny'],'Swinub':['Piloswine','Mamoswine'],
  'Swirlix':['Slurpuff'],'Tadbulb':['Bellibolt'],
  'Taillow':['Swellow'],'Tandemaus':['Maushold'],
  'Tangela':['Tangrowth'],'Tarountula':['Spidops'],
  'Teddiursa':['Ursaring','Ursaluna'],'Tentacool':['Tentacruel'],
  'Tepig':['Pignite','Emboar'],'Thwackey':['Rillaboom'],
  'Timburr':['Gurdurr','Conkeldurr'],'Tinkatink':['Tinkatuff','Tinkaton'],
  'Tirtouga':['Carracosta'],'Toedscool':['Toedscruel'],
  'Togepi':['Togetic','Togekiss'],'Togetic':['Togekiss'],
  'Torchic':['Combusken','Blaziken'],'Torracat':['Incineroar'],
  'Totodile':['Croconaw','Feraligatr'],'Toxel':['Toxtricity'],
  'Tranquill':['Unfezant'],'Trapinch':['Vibrava','Flygon'],
  'Treecko':['Grovyle','Sceptile'],'Trubbish':['Garbodor'],
  'Trumbeak':['Toucannon'],'Turtwig':['Grotle','Torterra'],
  'Tympole':['Palpitoad','Seismitoad'],'Tynamo':['Eelektrik','Eelektross'],
  'Tyrogue':['Hitmonlee','Hitmonchan','Hitmontop'],
  'Tyrunt':['Tyrantrum'],'Ursaring':['Ursaluna'],
  'Vanillish':['Vanilluxe'],'Vanillite':['Vanillish','Vanilluxe'],
  'Varoom':['Revavroom'],'Venipede':['Whirlipede','Scolipede'],
  'Venonat':['Venomoth'],'Vigoroth':['Slaking'],
  'Voltorb':['Electrode'],'Vullaby':['Mandibuzz'],'Vulpix':['Ninetales'],
  'Wailmer':['Wailord'],'Wartortle':['Blastoise'],'Wattrel':['Kilowattrel'],
  'Weedle':['Kakuna','Beedrill'],'Weepinbell':['Victreebel'],
  'Whirlipede':['Scolipede'],'Whismur':['Loudred','Exploud'],
  'Wiglett':['Wugtrio'],'Wimpod':['Golisopod'],'Wingull':['Pelipper'],
  'Woobat':['Swoobat'],'Wooloo':['Dubwool'],
  'Wooper':['Quagsire','Clodsire'],'Wurmple':['Silcoon','Cascoon'],
  'Wynaut':['Wobbuffet'],'Yamask':['Cofagrigus','Runerigus'],
  'Yamper':['Boltund'],'Yanma':['Yanmega'],'Yungoos':['Gumshoos'],
  'Zigzagoon':['Linoone','Obstagoon'],'Zorua':['Zoroark'],
  'Zubat':['Golbat','Crobat'],'Zweilous':['Hydreigon'],
};

// ═══════════════════════════════════════════════
// COLLECTION COMPLETION CONFIG
// Species where you want to collect all forms/patterns
// target: how many to keep (one per pattern/trim + spares)
// ═══════════════════════════════════════════════
const COLLECTION_SETS = {
  'Vivillon':   { forms: ['Archipelago','Continental','Elegant','Fancy','Garden','High Plains',
                          'Icy Snow','Jungle','Marine','Meadow','Modern','Monsoon','Ocean',
                          'Polar','River','Sandstorm','Savanna','Sun','Tundra','Poké Ball'],
                  target: 20, label: 'Vivillon patterns' },
  'Scatterbug': { forms: ['Archipelago','Continental','Elegant','Fancy','Garden','High Plains',
                          'Icy Snow','Jungle','Marine','Meadow','Modern','Monsoon','Ocean',
                          'Polar','River','Sandstorm','Savanna','Sun','Tundra','Poké Ball'],
                  target: 20, label: 'Scatterbug patterns' },
  'Furfrou':    { forms: ['Natural','Heart','Star','Diamond','Debutante','Matron',
                          'Dandy','La Reine','Kabuki','Pharaoh'],
                  target: 10, label: 'Furfrou trims' },
  'Flabébé':    { forms: ['Red','Yellow','Orange','Blue','White'], target: 5, label: 'Flabébé colours' },
  'Floette':    { forms: ['Red','Yellow','Orange','Blue','White'], target: 5, label: 'Floette colours' },
  'Florges':    { forms: ['Red','Yellow','Orange','Blue','White'], target: 5, label: 'Florges colours' },
};
